trigger:
  branches:
    include:
      - 'master' # Trigger on changes to the main branch

jobs:
- job: SemanticVersioning
  displayName: 'Semantic Versioning and Tagging'
  pool:
    name: Default
  steps:
  - checkout: self
    fetchDepth: 0

  - powershell: |
      # Call the versioning script
      .\update_version.ps1
    displayName: 'Run Versioning Script'
    env:
      GIT_PAT: $(GIT_PAT) # Use the PAT as an environment variable
